import type { Metadata } from "next";
import { Inter, Lato } from "next/font/google";
import "./globals.css";
import { classNameCombiner } from "@/utils";
import Header from "@/components/Header/header";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-in",
});
const lato = Lato({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lato",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={classNameCombiner(
          inter.variable,
          lato.variable,
          "font-lato bg-light dark:bg-dark"
        )}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
